/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package assignment;

import static assignment.DBConnection.con;
import static assignment.ManageResidentForm1.Username;
import static assignment.ManageResidentForm1.UnitNo1;
import static assignment.ManageResidentForm1.Phonenumber;
import static assignment.ManageResidentForm1.Email;
import static assignment.ManageResidentForm1.ResidentID;
import java.awt.event.KeyEvent;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import java.util.regex.Pattern;
import javax.swing.JFrame;
import javax.swing.JOptionPane;

/**
 *
 * @author Keith
 */
public class EditResidentForm extends javax.swing.JFrame {
    public static String username;
    /**
     * Creates new form DeleteResidentForm
     */
    public EditResidentForm() {
        initComponents();
                             
            
        UsernameTxt.setText(Username);
        UnitNoTxt.setText(UnitNo1);
        PhoneTxt.setText(Phonenumber);
        EmailTxt.setText(Email);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        UsernameLab = new javax.swing.JLabel();
        EditBut = new javax.swing.JButton();
        UnitNoLab = new javax.swing.JLabel();
        PhoneLab = new javax.swing.JLabel();
        EmailLab = new javax.swing.JLabel();
        UnitNoTxt = new javax.swing.JTextField();
        PhoneTxt = new javax.swing.JTextField();
        EmailTxt = new javax.swing.JTextField();
        BackLab = new javax.swing.JLabel();
        HomeLab = new javax.swing.JLabel();
        UsernameTxt = new javax.swing.JTextField();
        jPanel1 = new javax.swing.JPanel();
        CloseLab = new javax.swing.JLabel();
        EditPageLab = new javax.swing.JLabel();
        MinLab = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        jPanel2.setBackground(new java.awt.Color(0, 0, 0));

        UsernameLab.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        UsernameLab.setForeground(new java.awt.Color(255, 204, 204));
        UsernameLab.setText("Username:");

        EditBut.setBackground(new java.awt.Color(0, 0, 0));
        EditBut.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        EditBut.setForeground(new java.awt.Color(255, 204, 204));
        EditBut.setText("Edit");
        EditBut.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 204, 204)));
        EditBut.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        EditBut.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EditButActionPerformed(evt);
            }
        });

        UnitNoLab.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        UnitNoLab.setForeground(new java.awt.Color(255, 204, 204));
        UnitNoLab.setText("Unit No. :");

        PhoneLab.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        PhoneLab.setForeground(new java.awt.Color(255, 204, 204));
        PhoneLab.setText("Phone:");

        EmailLab.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        EmailLab.setForeground(new java.awt.Color(255, 204, 204));
        EmailLab.setText("Email:");

        UnitNoTxt.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        UnitNoTxt.setEnabled(false);

        PhoneTxt.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                PhoneTxtKeyTyped(evt);
            }
        });

        BackLab.setForeground(new java.awt.Color(255, 204, 204));
        BackLab.setText("Back");
        BackLab.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        BackLab.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                BackLabMouseClicked(evt);
            }
        });

        HomeLab.setForeground(new java.awt.Color(255, 204, 204));
        HomeLab.setText("Home");
        HomeLab.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        HomeLab.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                HomeLabMouseClicked(evt);
            }
        });

        UsernameTxt.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                UsernameTxtKeyTyped(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(BackLab)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(HomeLab)
                        .addGap(25, 25, 25))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(28, 28, 28)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(EmailLab)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(EmailTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(UnitNoLab)
                                    .addComponent(PhoneLab))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(UnitNoTxt, javax.swing.GroupLayout.DEFAULT_SIZE, 150, Short.MAX_VALUE)
                                    .addComponent(PhoneTxt)))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(UsernameLab)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(UsernameTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(56, 56, 56)
                        .addComponent(EditBut, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(52, 52, 52))))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(BackLab)
                    .addComponent(HomeLab))
                .addGap(34, 34, 34)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(UsernameLab)
                    .addComponent(UsernameTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(45, 45, 45)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(UnitNoLab)
                            .addComponent(UnitNoTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(69, 69, 69)
                        .addComponent(EditBut, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(PhoneLab)
                    .addComponent(PhoneTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(41, 41, 41)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(EmailLab)
                    .addComponent(EmailTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(124, 124, 124))
        );

        jPanel1.setBackground(new java.awt.Color(255, 178, 178));

        CloseLab.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        CloseLab.setForeground(new java.awt.Color(255, 255, 255));
        CloseLab.setText("X");
        CloseLab.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        CloseLab.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                CloseLabMouseClicked(evt);
            }
        });

        EditPageLab.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        EditPageLab.setForeground(new java.awt.Color(255, 255, 255));
        EditPageLab.setText("Edit Page");

        MinLab.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        MinLab.setForeground(new java.awt.Color(255, 255, 255));
        MinLab.setText("-");
        MinLab.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        MinLab.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                MinLabMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(EditPageLab)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 427, Short.MAX_VALUE)
                .addComponent(MinLab)
                .addGap(18, 18, 18)
                .addComponent(CloseLab)
                .addGap(23, 23, 23))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(CloseLab, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(MinLab, javax.swing.GroupLayout.DEFAULT_SIZE, 33, Short.MAX_VALUE)
                    .addComponent(EditPageLab, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(1, 1, 1)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 360, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void EditButActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EditButActionPerformed
        //Connect to database
        DBConnection conn = new DBConnection();
        conn.connection();
        PreparedStatement ps,ps1,ps2,ps3;
        
        //Declare variables
        int Check_Username = 0,Check_PhoneNumber = 0,Check_Email = 0;
        String PhoneNumber,email,UnitNo;
        username = UsernameTxt.getText();
        UnitNo = UnitNoTxt.getText();
        PhoneNumber = PhoneTxt.getText();
        email = EmailTxt.getText();
               
        //Confirmation Box before Edit
        int option = JOptionPane.showConfirmDialog(this,"Edit these records?","Confirmation Message",JOptionPane.YES_NO_OPTION,JOptionPane.WARNING_MESSAGE);
        
        if(option == 0){
            //Validation
            if(username.length()>50){
                JOptionPane.showMessageDialog(this,"Username must be less than 50 characters.","Validation Message",JOptionPane.ERROR_MESSAGE);
            }else if(username.length()<1){
                JOptionPane.showMessageDialog(this,"Username cannot be null","Validation Message",JOptionPane.ERROR_MESSAGE);
            }else if(PhoneNumber.length()>11 ){
                JOptionPane.showMessageDialog(this,"Phone Number cannot longer than 11 number","Validation Message",JOptionPane.ERROR_MESSAGE);
            }else if(PhoneNumber.length()<1){
                JOptionPane.showMessageDialog(this,"Phone Number cannot be null","Validation Message",JOptionPane.ERROR_MESSAGE);
            }else if(PhoneNumber.length()<10){
                JOptionPane.showMessageDialog(this,"Invalid Phone Number","Validation Message",JOptionPane.ERROR_MESSAGE);
            }else if(!Pattern.matches("^[a-zA-Z0-9.!#$%&'*+/=?^_`{|}~-]+@((\\[[0-9]{1,3}\\.[0-9]{1,3}\\.[0-9]{1,3}\\.[0-9]{1,3}\\])|(([a-zA-Z\\-0-9]+\\.)+[a-zA-Z]{2,}))$",email)){
                JOptionPane.showMessageDialog(this,"Invalid Email","Validation Message",JOptionPane.ERROR_MESSAGE);
            }else{
                
                //To check the changes on username
                //Username changed
                if(!(username.equals(Username))){
                    
                    try{
                        //SQL Select query to check the availability of the new username 
                        ps = con.prepareStatement("SELECT * FROM `resident` WHERE `Resident_Name`=? AND (`Account_Status` = \"Active\" OR `Account_Status` = \"Deactivated\")");
                        ps.setString(1,username);
                        ResultSet result = ps.executeQuery();
                        
                        if(result.next()){
                            Check_Username = 1;
                        }
                        
                    } catch (SQLException ex) {
                        Logger.getLogger(ResidentMenuForm.class.getName()).log(Level.SEVERE, null, ex);
                    }
                }
                    
                //To check the changes on phone number
                //Phone Number Changed
                if(!(PhoneNumber.equals(Phonenumber))){
                                   
                    try{
                        //SQL Select query to check the availability of the new phone number
                        ps1 = con.prepareStatement("SELECT * FROM `resident` WHERE `Resident_Phone_Number`=? AND (`Account_Status` = \"Active\" OR `Account_Status` = \"Deactivated\")");
                        ps1.setString(1,PhoneNumber);
                        ResultSet result1 = ps1.executeQuery();
                        
                        if(result1.next()){
                            Check_PhoneNumber = 2;
                        }
                        
                    } catch (SQLException ex) {
                        Logger.getLogger(ResidentMenuForm.class.getName()).log(Level.SEVERE, null, ex);
                    }
                }
                
                //To check the changes on email
                //Email Changed
                if(!(email.equals(Email))){
                                    
                    try{
                        //SQL Select query to check the availability of the new email
                        ps2 = con.prepareStatement("SELECT * FROM `resident` WHERE `Resident_Email`=? AND (`Account_Status` = \"Active\" OR `Account_Status` = \"Deactivated\")");
                        ps2.setString(1,email);
                        ResultSet result2 = ps2.executeQuery();
                        
                        if(result2.next()){
                            Check_Email = 3;
                        }
                        
                    } catch (SQLException ex) {
                        Logger.getLogger(ResidentMenuForm.class.getName()).log(Level.SEVERE, null, ex);
                    }
                }
                
                System.out.println(Check_Username);
                System.out.println(Check_PhoneNumber);
                System.out.println(Check_Email);
                if(Check_Username == 1){
                    JOptionPane.showMessageDialog(this,"This username is registered.","Validation Message",JOptionPane.ERROR_MESSAGE);
                }else if(Check_PhoneNumber == 2){
                    JOptionPane.showMessageDialog(this,"This phone number is registered.","Validation Message",JOptionPane.ERROR_MESSAGE);
                }else if(Check_Email == 3){
                    JOptionPane.showMessageDialog(this,"This email is registered.","Validation Message",JOptionPane.ERROR_MESSAGE);
                }else{
                    try {
                        //SQL UPDATE Query to update the info in the Resident table
                        ps3 = con.prepareStatement("UPDATE `resident` SET `Resident_Name`=?,`Resident_Phone_Number`=?,`Resident_Email`=? WHERE `Resident_ID` =?");
                        ps3.setString(1,username);
                        ps3.setString(2,PhoneNumber);
                        ps3.setString(3,email);
                        ps3.setString(4,ResidentID);
                        ps3.executeUpdate();
                        
                        JOptionPane.showMessageDialog(this,"Edit Successfully!","Edit Message",JOptionPane.INFORMATION_MESSAGE);
                        
                        ManageResidentForm1 mrf1 = new ManageResidentForm1();
                        mrf1.setVisible(true);
                        mrf1.pack();
                        mrf1.setLocationRelativeTo(null);
                        mrf1.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
                        this.setVisible(false);
                    } catch (SQLException ex) {
                        Logger.getLogger(ResidentMenuForm.class.getName()).log(Level.SEVERE, null, ex);
                    }
                }
                
                        
                    
                
            }
        }
    }//GEN-LAST:event_EditButActionPerformed

    private void CloseLabMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_CloseLabMouseClicked
        System.exit(0);//Close Button
    }//GEN-LAST:event_CloseLabMouseClicked

    private void MinLabMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_MinLabMouseClicked
        this.setState(JFrame.ICONIFIED);//Minimize Button
    }//GEN-LAST:event_MinLabMouseClicked

    private void BackLabMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BackLabMouseClicked
        //Confirmation Box before going back
        int option = JOptionPane.showConfirmDialog(null,"Want to go back?\nThe data changed are unsaved.","Confirmation Message",JOptionPane.YES_NO_OPTION,JOptionPane.QUESTION_MESSAGE);
        
        if(option == 0){        
        ManageResidentForm2 mrf2 = new ManageResidentForm2();
        mrf2.setVisible(true);
        mrf2.pack();
        mrf2.setLocationRelativeTo(null);
        mrf2.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        this.setVisible(false);
        }
    }//GEN-LAST:event_BackLabMouseClicked

    private void HomeLabMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_HomeLabMouseClicked
        //Confirmation Box before go back to Home Page
        int option = JOptionPane.showConfirmDialog(null,"Want to exit this page?\nThe data changed are unsaved.","Confirmation Message",JOptionPane.YES_NO_OPTION,JOptionPane.QUESTION_MESSAGE);
        
        if(option == 0){
        //Open Staff Menu Form
        StaffMenuForm smf = new StaffMenuForm();
        smf.setVisible(true);
        smf.pack();
        smf.setLocationRelativeTo(null);
        smf.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        this.setVisible(false);
        }
    }//GEN-LAST:event_HomeLabMouseClicked

    private void UsernameTxtKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_UsernameTxtKeyTyped
        //Validate the user can type lowercase Alpabet and space only
        char c = evt.getKeyChar();
        if(!(c== KeyEvent.VK_BACK_SPACE || c== KeyEvent.VK_DELETE || Character.isWhitespace(c)|| Character.isLowerCase(c))){
            evt.consume();
            JOptionPane.showMessageDialog(this,"Lower Case Alphabet Only!","Validation Message",JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_UsernameTxtKeyTyped

    private void PhoneTxtKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_PhoneTxtKeyTyped
        //Validate the user can type Digit only
        char c = evt.getKeyChar();
        if(!(Character.isDigit(c) || c== KeyEvent.VK_BACK_SPACE || c== KeyEvent.VK_DELETE )){
            evt.consume();
            JOptionPane.showMessageDialog(this,"Digit Only!","Validation Message",JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_PhoneTxtKeyTyped

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(EditResidentForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(EditResidentForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(EditResidentForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(EditResidentForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new EditResidentForm().setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel BackLab;
    private javax.swing.JLabel CloseLab;
    private javax.swing.JButton EditBut;
    private javax.swing.JLabel EditPageLab;
    private javax.swing.JLabel EmailLab;
    private javax.swing.JTextField EmailTxt;
    private javax.swing.JLabel HomeLab;
    private javax.swing.JLabel MinLab;
    private javax.swing.JLabel PhoneLab;
    private javax.swing.JTextField PhoneTxt;
    private javax.swing.JLabel UnitNoLab;
    private javax.swing.JTextField UnitNoTxt;
    private javax.swing.JLabel UsernameLab;
    private javax.swing.JTextField UsernameTxt;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    // End of variables declaration//GEN-END:variables
}
