/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package assignment;

import static assignment.DBConnection.con;
import static assignment.ManageResidentForm1.Username;
import static assignment.ManageResidentForm1.UnitNo1;
import static assignment.ManageResidentForm1.Phonenumber;
import static assignment.ManageResidentForm1.Email;
import static assignment.ManageResidentForm1.Outstandingbalance;
import static assignment.ManageResidentForm1.Duedate;
import static assignment.ManageResidentForm1.Account_Status;
import java.sql.PreparedStatement;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFrame;
import javax.swing.JOptionPane;

/**
 *
 * @author Keith
 */
public class ManageResidentForm2 extends javax.swing.JFrame {
    public static String UnitNoFromMRF2;
    /**
     * Creates new form ManageResidentForm2
     */
    public ManageResidentForm2() {
        initComponents();
        
        AccStatusTxt.setText(Account_Status);
        UsernameTxt.setText(Username);
        UnitNoTxt.setText(UnitNo1);
        PhoneTxt.setText(Phonenumber);
        EmailTxt.setText(Email);
        OutstandingTxt.setText(Integer.toString(Outstandingbalance));
        DueDateTxt.setText(String.valueOf(Duedate));
                
        if(DueDateTxt.getText().equals("null")){
           DueDateTxt.setText("                        ---"); 
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        UsernameLab = new javax.swing.JLabel();
        EditBut = new javax.swing.JButton();
        UnitNoLab = new javax.swing.JLabel();
        PhoneLab = new javax.swing.JLabel();
        EmailLab = new javax.swing.JLabel();
        UsernameTxt = new javax.swing.JTextField();
        PhoneTxt = new javax.swing.JTextField();
        EmailTxt = new javax.swing.JTextField();
        BackLab = new javax.swing.JLabel();
        HomeLab = new javax.swing.JLabel();
        DeleteBut = new javax.swing.JButton();
        BalanceLab = new javax.swing.JLabel();
        OutstandingTxt = new javax.swing.JTextField();
        OutstandingLab = new javax.swing.JLabel();
        DueDateLab = new javax.swing.JLabel();
        DueDateTxt = new javax.swing.JTextField();
        UnitNoTxt = new javax.swing.JTextField();
        PayBut = new javax.swing.JButton();
        AccStatusTxt = new javax.swing.JTextField();
        AccStatusLab = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        CloseLab = new javax.swing.JLabel();
        ManagePage2Lab = new javax.swing.JLabel();
        MinLab = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        jPanel2.setBackground(new java.awt.Color(0, 0, 0));

        UsernameLab.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        UsernameLab.setForeground(new java.awt.Color(255, 204, 204));
        UsernameLab.setText("Username:");

        EditBut.setBackground(new java.awt.Color(0, 0, 0));
        EditBut.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        EditBut.setForeground(new java.awt.Color(255, 204, 204));
        EditBut.setText("Edit");
        EditBut.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 204, 204)));
        EditBut.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        EditBut.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EditButActionPerformed(evt);
            }
        });

        UnitNoLab.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        UnitNoLab.setForeground(new java.awt.Color(255, 204, 204));
        UnitNoLab.setText("Unit No. :");

        PhoneLab.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        PhoneLab.setForeground(new java.awt.Color(255, 204, 204));
        PhoneLab.setText("Phone:");

        EmailLab.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        EmailLab.setForeground(new java.awt.Color(255, 204, 204));
        EmailLab.setText("Email:");

        UsernameTxt.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        UsernameTxt.setEnabled(false);

        PhoneTxt.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        PhoneTxt.setEnabled(false);

        EmailTxt.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        EmailTxt.setEnabled(false);

        BackLab.setForeground(new java.awt.Color(255, 204, 204));
        BackLab.setText("Back");
        BackLab.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        BackLab.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                BackLabMouseClicked(evt);
            }
        });

        HomeLab.setForeground(new java.awt.Color(255, 204, 204));
        HomeLab.setText("Home");
        HomeLab.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        HomeLab.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                HomeLabMouseClicked(evt);
            }
        });

        DeleteBut.setBackground(new java.awt.Color(0, 0, 0));
        DeleteBut.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        DeleteBut.setForeground(new java.awt.Color(255, 204, 204));
        DeleteBut.setText("Delete");
        DeleteBut.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 204, 204)));
        DeleteBut.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        DeleteBut.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DeleteButActionPerformed(evt);
            }
        });

        BalanceLab.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        BalanceLab.setForeground(new java.awt.Color(255, 204, 204));
        BalanceLab.setText("Balance:");

        OutstandingTxt.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        OutstandingTxt.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        OutstandingTxt.setEnabled(false);
        OutstandingTxt.setPreferredSize(new java.awt.Dimension(35, 27));

        OutstandingLab.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        OutstandingLab.setForeground(new java.awt.Color(255, 204, 204));
        OutstandingLab.setText("Outstanding");

        DueDateLab.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        DueDateLab.setForeground(new java.awt.Color(255, 204, 204));
        DueDateLab.setText("Due Date:");

        DueDateTxt.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        DueDateTxt.setEnabled(false);

        UnitNoTxt.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        UnitNoTxt.setEnabled(false);

        PayBut.setBackground(new java.awt.Color(0, 0, 0));
        PayBut.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        PayBut.setForeground(new java.awt.Color(255, 204, 204));
        PayBut.setText("Pay");
        PayBut.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 204, 204)));
        PayBut.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        PayBut.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PayButActionPerformed(evt);
            }
        });

        AccStatusTxt.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        AccStatusTxt.setEnabled(false);

        AccStatusLab.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        AccStatusLab.setForeground(new java.awt.Color(255, 204, 204));
        AccStatusLab.setText("Acc Status:");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(UsernameLab)
                            .addComponent(UnitNoLab)
                            .addComponent(EmailLab)
                            .addComponent(PhoneLab)
                            .addComponent(DueDateLab))
                        .addGap(74, 74, 74)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(DueDateTxt)
                            .addComponent(PhoneTxt)
                            .addComponent(EmailTxt, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(UnitNoTxt)
                            .addComponent(UsernameTxt)
                            .addComponent(AccStatusTxt))
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(73, 73, 73)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(OutstandingTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(PayBut, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(EditBut, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(DeleteBut, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(10, 10, 10))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(BalanceLab)
                                .addGap(18, 18, 18))))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(BackLab)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(HomeLab))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(AccStatusLab)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(OutstandingLab)))
                .addGap(44, 44, 44))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(BackLab)
                    .addComponent(HomeLab))
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(36, 36, 36)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(AccStatusTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(AccStatusLab)))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(OutstandingLab)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(BalanceLab)))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(UsernameTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(UsernameLab))
                        .addGap(26, 26, 26)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(UnitNoTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(UnitNoLab)))
                    .addComponent(OutstandingTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(26, 26, 26)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(EmailTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(EmailLab)))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addComponent(PayBut, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(PhoneTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(PhoneLab)
                            .addComponent(EditBut, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(DueDateTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(DeleteBut, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(3, 3, 3))
                    .addComponent(DueDateLab))
                .addContainerGap(59, Short.MAX_VALUE))
        );

        jPanel1.setBackground(new java.awt.Color(255, 178, 178));

        CloseLab.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        CloseLab.setForeground(new java.awt.Color(255, 255, 255));
        CloseLab.setText("X");
        CloseLab.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        CloseLab.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                CloseLabMouseClicked(evt);
            }
        });

        ManagePage2Lab.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        ManagePage2Lab.setForeground(new java.awt.Color(255, 255, 255));
        ManagePage2Lab.setText("Manage Page");

        MinLab.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        MinLab.setForeground(new java.awt.Color(255, 255, 255));
        MinLab.setText("-");
        MinLab.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        MinLab.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                MinLabMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(ManagePage2Lab)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 389, Short.MAX_VALUE)
                .addComponent(MinLab)
                .addGap(18, 18, 18)
                .addComponent(CloseLab)
                .addGap(23, 23, 23))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(CloseLab, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(MinLab, javax.swing.GroupLayout.DEFAULT_SIZE, 33, Short.MAX_VALUE)
                    .addComponent(ManagePage2Lab, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(50, 50, 50)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void EditButActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EditButActionPerformed
        EditResidentForm erf = new EditResidentForm();
        erf.setVisible(true);
        erf.pack();
        erf.setLocationRelativeTo(null);
        erf.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        this.setVisible(false);
    }//GEN-LAST:event_EditButActionPerformed

    private void CloseLabMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_CloseLabMouseClicked
        System.exit(0);//Close Button
    }//GEN-LAST:event_CloseLabMouseClicked

    private void MinLabMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_MinLabMouseClicked
        this.setState(JFrame.ICONIFIED);//Minimize Button
    }//GEN-LAST:event_MinLabMouseClicked

    private void DeleteButActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DeleteButActionPerformed
        //Connect to database
        DBConnection conn = new DBConnection();
        conn.connection();
        PreparedStatement ps,ps1;
        int check;
        
        //Confirmation Box before Delete
        int option = JOptionPane.showConfirmDialog(this,"Delete this resident?\nThe data deleted cannot be recover.","Confirmation Message",JOptionPane.YES_NO_OPTION,JOptionPane.WARNING_MESSAGE);
        
        if(option == 0){
                      
            try {
                
                if(Outstandingbalance > 0){
                    //Remind to pay the OutstandingBalance
                    JOptionPane.showMessageDialog(this,"Please pay before delete this resident!","Delete Message",JOptionPane.WARNING_MESSAGE);
                }else{
                //SQL UPDATE Query to update the Password in the resident table
                ps = con.prepareStatement("UPDATE `resident` SET `Resident_Password` = NULL,`Account_Status`= 'Deleted' WHERE `Resident_Name` = ?");
                ps.setString(1,Username);
                ps.executeUpdate();
                check = 1;
                
                if(check == 1){
                //SQL UPDATE Query to reset the info in the unit table
                ps1 = con.prepareStatement("UPDATE `unit` SET `Unit_Register_Date`=NULL,`Resident_ID`=NULL,`Outstanding_Balance`=NULL,`Due_Date`=NULL WHERE `Unit_ID` = ?");
                ps1.setString(1,UnitNo1);
                ps1.executeUpdate();
                check = 2;
                }
                
                if(check == 2){
                //Delete Successfully Message 
                JOptionPane.showMessageDialog(this,"Delete Successfully!","Delete Message",JOptionPane.INFORMATION_MESSAGE);
                
                //Open Staff Menu Form
                StaffMenuForm smf = new StaffMenuForm();
                smf.setVisible(true);
                smf.pack();
                smf.setLocationRelativeTo(null);
                smf.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
                this.setVisible(false);
                }
                }
            } catch (SQLException ex) {
                Logger.getLogger(ManageResidentForm2.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
    }//GEN-LAST:event_DeleteButActionPerformed

    private void HomeLabMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_HomeLabMouseClicked
        StaffMenuForm smf = new StaffMenuForm();
        smf.setVisible(true);
        smf.pack();
        smf.setLocationRelativeTo(null);
        smf.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        this.setVisible(false);
    }//GEN-LAST:event_HomeLabMouseClicked

    private void BackLabMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BackLabMouseClicked
        ManageResidentForm1 mrf1 = new ManageResidentForm1();
        mrf1.setVisible(true);
        mrf1.pack();
        mrf1.setLocationRelativeTo(null);
        mrf1.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        this.setVisible(false);
    }//GEN-LAST:event_BackLabMouseClicked

    private void PayButActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PayButActionPerformed
        
        if(Outstandingbalance == 0 || Duedate == null){
            //Message to remind no need pay 
            JOptionPane.showMessageDialog(this,"No outstanding balance.","Outstanding Balance Message",JOptionPane.INFORMATION_MESSAGE);
        }else{
            UnitNoFromMRF2 = UnitNoTxt.getText();
            PaymentForm1 pf1 = new PaymentForm1();
            pf1.setVisible(true);
            pf1.pack();
            pf1.setLocationRelativeTo(null);
            pf1.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
            this.setVisible(false);            
        }
    }//GEN-LAST:event_PayButActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ManageResidentForm2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ManageResidentForm2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ManageResidentForm2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ManageResidentForm2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new ManageResidentForm2().setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel AccStatusLab;
    private javax.swing.JTextField AccStatusTxt;
    private javax.swing.JLabel BackLab;
    private javax.swing.JLabel BalanceLab;
    private javax.swing.JLabel CloseLab;
    private javax.swing.JButton DeleteBut;
    private javax.swing.JLabel DueDateLab;
    private javax.swing.JTextField DueDateTxt;
    private javax.swing.JButton EditBut;
    private javax.swing.JLabel EmailLab;
    private javax.swing.JTextField EmailTxt;
    private javax.swing.JLabel HomeLab;
    private javax.swing.JLabel ManagePage2Lab;
    private javax.swing.JLabel MinLab;
    private javax.swing.JLabel OutstandingLab;
    private javax.swing.JTextField OutstandingTxt;
    private javax.swing.JButton PayBut;
    private javax.swing.JLabel PhoneLab;
    private javax.swing.JTextField PhoneTxt;
    private javax.swing.JLabel UnitNoLab;
    private javax.swing.JTextField UnitNoTxt;
    private javax.swing.JLabel UsernameLab;
    private javax.swing.JTextField UsernameTxt;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    // End of variables declaration//GEN-END:variables
}
