/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package assignment;

import static assignment.DBConnection.con;
import static assignment.PaymentForm1.UnitNo;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.text.DateFormat;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFrame;
import javax.swing.JOptionPane;

/**
 *
 * @author Keith
 */
public class PaymentForm2 extends javax.swing.JFrame {
    public static int Fine,total,OutstandingBalance;
    public static String ResidentName,UnitNoFromPF2;
    /**
     * Creates new form PaymentForm2
     */
    public PaymentForm2() {
        try {
            initComponents();
            
            //Set value to text box 
            UnitNoTxt.setText(UnitNo);
            
            //Declare variables
            PreparedStatement ps,ps1;
            //Declare variable for the current date
            DateFormat dateFormat = new SimpleDateFormat("yyyy/MM/dd");
            Date CurrentDate = new Date();
                        
            //SQL Select query to get Outstanding Balance,Due Date and Resident ID from Unit table
            ps = con.prepareStatement("SELECT `Outstanding_Balance`, `Due_Date`,`Resident_ID` FROM `unit` WHERE `Unit_ID`=?");
            ps.setString(1,UnitNo);
            ResultSet result = ps.executeQuery();
            
            result.next();
            OutstandingBalance = result.getInt("Outstanding_Balance");
            Date DueDate = result.getDate("Due_Date");
            String ResidentID = result.getString("Resident_ID");
            
            
            //SQL Select query to get Outstanding Balance and Due Date from Unit table
            ps1 = con.prepareStatement("SELECT `Resident_Name` FROM `resident` WHERE `Resident_ID` = ?");
            ps1.setString(1,ResidentID);
            ResultSet result1 = ps1.executeQuery();
            
            result1.next();
            ResidentName = result1.getString("Resident_Name");
            
            
            //Set values to the text box
            //Username
            UsernameTxt.setText(ResidentName);
            //Outstanding Balance
            OutstandingBalanceTxt.setText(Integer.toString(OutstandingBalance));
            
            
            //Fine
            //Current Date is after Due Date
            if(dateFormat.format(CurrentDate).compareTo(dateFormat.format(DueDate))>0){
                FineTxt.setText("50");
            //Current Date is before Due Date    
            }else if(dateFormat.format(CurrentDate).compareTo(dateFormat.format(DueDate))<0){
                FineTxt.setText("0");
            //Current date is equal to Due Date
            }else if(dateFormat.format(CurrentDate).compareTo(dateFormat.format(DueDate)) == 0){
                FineTxt.setText("0");
            }
            
            //Total
            Fine = Integer.parseInt(FineTxt.getText());
            total = OutstandingBalance + Fine;
            TotalTxt.setText(Integer.toString(total));
            
            
        } catch (SQLException ex) {
            Logger.getLogger(PaymentForm2.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        PayBut = new javax.swing.JButton();
        BackLab = new javax.swing.JLabel();
        HomeLab = new javax.swing.JLabel();
        UnitNoLab = new javax.swing.JLabel();
        OutstandingBalanceLab = new javax.swing.JLabel();
        UsernameLab = new javax.swing.JLabel();
        UsernameTxt = new javax.swing.JTextField();
        UnitNoTxt = new javax.swing.JTextField();
        OutstandingBalanceTxt = new javax.swing.JTextField();
        FineTxt = new javax.swing.JTextField();
        FineLab = new javax.swing.JLabel();
        TotalTxt = new javax.swing.JTextField();
        TotalLab = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        CloseLab = new javax.swing.JLabel();
        PaymentPage2Lab = new javax.swing.JLabel();
        MinLab = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        jPanel2.setBackground(new java.awt.Color(0, 0, 0));

        PayBut.setBackground(new java.awt.Color(0, 0, 0));
        PayBut.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        PayBut.setForeground(new java.awt.Color(255, 204, 204));
        PayBut.setText("Pay");
        PayBut.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 204, 204)));
        PayBut.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        PayBut.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PayButActionPerformed(evt);
            }
        });

        BackLab.setForeground(new java.awt.Color(255, 204, 204));
        BackLab.setText("Back");
        BackLab.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        BackLab.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                BackLabMouseClicked(evt);
            }
        });

        HomeLab.setForeground(new java.awt.Color(255, 204, 204));
        HomeLab.setText("Home");
        HomeLab.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        HomeLab.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                HomeLabMouseClicked(evt);
            }
        });

        UnitNoLab.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        UnitNoLab.setForeground(new java.awt.Color(255, 204, 204));
        UnitNoLab.setText("Unit No. :");

        OutstandingBalanceLab.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        OutstandingBalanceLab.setForeground(new java.awt.Color(255, 204, 204));
        OutstandingBalanceLab.setText("Outstanding Balance:");

        UsernameLab.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        UsernameLab.setForeground(new java.awt.Color(255, 204, 204));
        UsernameLab.setText("Username:");

        UsernameTxt.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        UsernameTxt.setEnabled(false);

        UnitNoTxt.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        UnitNoTxt.setEnabled(false);

        OutstandingBalanceTxt.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        OutstandingBalanceTxt.setEnabled(false);

        FineTxt.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        FineTxt.setEnabled(false);

        FineLab.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        FineLab.setForeground(new java.awt.Color(255, 204, 204));
        FineLab.setText("Fine:");

        TotalTxt.setForeground(new java.awt.Color(255, 0, 0));
        TotalTxt.setDisabledTextColor(new java.awt.Color(255, 0, 0));
        TotalTxt.setEnabled(false);

        TotalLab.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        TotalLab.setForeground(new java.awt.Color(255, 204, 204));
        TotalLab.setText("Total:");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addComponent(BackLab)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(HomeLab)
                .addGap(25, 25, 25))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(TotalLab)
                        .addGap(83, 83, 83)
                        .addComponent(TotalTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(FineLab)
                        .addGap(83, 83, 83)
                        .addComponent(FineTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(UnitNoLab)
                        .addGap(83, 83, 83)
                        .addComponent(UnitNoTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                                .addGap(174, 174, 174)
                                .addComponent(UsernameLab)
                                .addGap(84, 84, 84))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(67, 67, 67)
                                .addComponent(OutstandingBalanceLab)
                                .addGap(83, 83, 83)))
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(UsernameTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(OutstandingBalanceTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(89, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(PayBut, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(246, 246, 246))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(BackLab)
                    .addComponent(HomeLab))
                .addGap(37, 37, 37)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(UsernameLab)
                    .addComponent(UsernameTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(UnitNoLab)
                    .addComponent(UnitNoTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(53, 53, 53)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(OutstandingBalanceLab)
                    .addComponent(OutstandingBalanceTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(FineLab)
                    .addComponent(FineTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(TotalLab)
                    .addComponent(TotalTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(41, 41, 41)
                .addComponent(PayBut, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(48, Short.MAX_VALUE))
        );

        jPanel1.setBackground(new java.awt.Color(255, 178, 178));

        CloseLab.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        CloseLab.setForeground(new java.awt.Color(255, 255, 255));
        CloseLab.setText("X");
        CloseLab.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        CloseLab.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                CloseLabMouseClicked(evt);
            }
        });

        PaymentPage2Lab.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        PaymentPage2Lab.setForeground(new java.awt.Color(255, 255, 255));
        PaymentPage2Lab.setText("Payment Page");

        MinLab.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        MinLab.setForeground(new java.awt.Color(255, 255, 255));
        MinLab.setText("-");
        MinLab.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        MinLab.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                MinLabMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(PaymentPage2Lab)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(MinLab)
                .addGap(18, 18, 18)
                .addComponent(CloseLab)
                .addGap(23, 23, 23))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(CloseLab, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(MinLab, javax.swing.GroupLayout.DEFAULT_SIZE, 33, Short.MAX_VALUE)
                    .addComponent(PaymentPage2Lab, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(1, 1, 1)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void PayButActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PayButActionPerformed
        try {
            PreparedStatement ps,ps1,ps2,ps3;
            //Declare variable for the current date
            DateFormat dateFormat = new SimpleDateFormat("yyyy/MM/dd");
            Date CurrentDate = new Date();
            //Declare variable to check the progress of the code
            int check;
            
            //SQL Select query to get Due Date and Resident ID from Unit table
            ps = con.prepareStatement("SELECT `Due_Date`,`Resident_ID` FROM `unit` WHERE `Unit_ID`=?");
            ps.setString(1,UnitNo);
            ResultSet result = ps.executeQuery();
            
            result.next();
            Date DueDate = result.getDate("Due_Date");
            String ResidentID = result.getString("Resident_ID");
            check = 1;
            
            if(check == 1){
            //SQL INSERT Query to insert payment's info into payment table
            ps1 = con.prepareStatement("INSERT INTO `payment`(`Payment_Date`, `Due_Date`, `Payment_Amount`, `Resident_ID`) VALUES (?,?,?,?)");
            ps1.setString(1,dateFormat.format(CurrentDate));
            ps1.setString(2,dateFormat.format(DueDate));
            ps1.setString(3,TotalTxt.getText());
            ps1.setString(4,ResidentID);
            ps1.executeUpdate();
            check = 2;
            }
            
            if(check == 2){
            //SQL UPDATE Query to reset the Outstanding Balance and Due Date in unit table
            ps2 = con.prepareStatement("UPDATE `unit` SET `Outstanding_Balance`= NULL, `Due_Date`= NULL WHERE `Unit_ID` = ?");
            ps2.setString(1,UnitNo); 
            ps2.executeUpdate();
            check = 3;
            }
            
            if(check == 3){
            //SQL UPDATE Query to set the account status to active in resident table 
            ps3 = con.prepareStatement("UPDATE `resident` SET `Account_Status`= \"Active\" WHERE `Resident_ID` = ?");
            ps3.setString(1,ResidentID); 
            ps3.executeUpdate();
            check = 4;
            }
            
            if(check == 4){
            JOptionPane.showMessageDialog(this,"Payment Done Successfully!","Payment Message",JOptionPane.INFORMATION_MESSAGE);
            
            //Open Receipt Form
            //Pass the value to the UnitNoFromPF2
            UnitNoFromPF2 = UnitNo;
            ReceiptForm rf = new ReceiptForm();
            rf.setVisible(true);
            rf.pack();
            rf.setLocationRelativeTo(null);
            rf.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
            this.setVisible(false);
        
            }else{
                JOptionPane.showMessageDialog(this,"Payment Failed!","Payment Message",JOptionPane.ERROR_MESSAGE);
            }
            
        } catch (SQLException ex) {
            Logger.getLogger(PaymentForm2.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_PayButActionPerformed

    private void CloseLabMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_CloseLabMouseClicked
        System.exit(0);//Close Button
    }//GEN-LAST:event_CloseLabMouseClicked

    private void MinLabMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_MinLabMouseClicked
        this.setState(JFrame.ICONIFIED);//Minimize Button
    }//GEN-LAST:event_MinLabMouseClicked

    private void BackLabMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BackLabMouseClicked
        //Confirmation Box before going back
        int option = JOptionPane.showConfirmDialog(null,"Want to go back?\nThe data changed are unsaved.","Confirmation Message",JOptionPane.YES_NO_OPTION,JOptionPane.QUESTION_MESSAGE);
        
        if(option == 0){
        PaymentForm1 pf1 = new PaymentForm1();
        pf1.setVisible(true);
        pf1.pack();
        pf1.setLocationRelativeTo(null);
        pf1.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        this.setVisible(false);
        }
    }//GEN-LAST:event_BackLabMouseClicked

    private void HomeLabMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_HomeLabMouseClicked
        //Confirmation Box before go back to Home Page
        int option = JOptionPane.showConfirmDialog(null,"Want to exit this page?\nThe data changed are unsaved.","Confirmation Message",JOptionPane.YES_NO_OPTION,JOptionPane.QUESTION_MESSAGE);
        
        if(option == 0){
        //Open Staff Menu Form
        StaffMenuForm smf = new StaffMenuForm();
        smf.setVisible(true);
        smf.pack();
        smf.setLocationRelativeTo(null);
        smf.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        this.setVisible(false);
        }
    }//GEN-LAST:event_HomeLabMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PaymentForm2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PaymentForm2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PaymentForm2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PaymentForm2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new PaymentForm2().setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel BackLab;
    private javax.swing.JLabel CloseLab;
    private javax.swing.JLabel FineLab;
    private javax.swing.JTextField FineTxt;
    private javax.swing.JLabel HomeLab;
    private javax.swing.JLabel MinLab;
    private javax.swing.JLabel OutstandingBalanceLab;
    private javax.swing.JTextField OutstandingBalanceTxt;
    private javax.swing.JButton PayBut;
    private javax.swing.JLabel PaymentPage2Lab;
    private javax.swing.JLabel TotalLab;
    private javax.swing.JTextField TotalTxt;
    private javax.swing.JLabel UnitNoLab;
    private javax.swing.JTextField UnitNoTxt;
    private javax.swing.JLabel UsernameLab;
    private javax.swing.JTextField UsernameTxt;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    // End of variables declaration//GEN-END:variables
}
