/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package assignment;

import static assignment.DBConnection.con;
import static assignment.ManageResidentForm2.UnitNoFromMRF2;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFrame;
import javax.swing.JOptionPane;

/**
 *
 * @author Keith
 */
public class PaymentForm1 extends javax.swing.JFrame {
    public static String UnitNo;
    /**
     * Creates new form PaymentForm1
     */
    public PaymentForm1() {
        initComponents();
        
        BlockCmb.requestFocus();
             
        if(UnitNoFromMRF2 == null){
            UnitCmb.removeAllItems();
        }else{
            UnitCmb.addItem(UnitNoFromMRF2);
            UnitCmb.setEnabled(true);
            
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        SelectBut = new javax.swing.JButton();
        BackLab = new javax.swing.JLabel();
        UnitNoLab = new javax.swing.JLabel();
        UnitCmb = new javax.swing.JComboBox<>();
        BlockLab = new javax.swing.JLabel();
        BlockCmb = new javax.swing.JComboBox<>();
        FloorLab = new javax.swing.JLabel();
        FloorCmb = new javax.swing.JComboBox<>();
        jPanel1 = new javax.swing.JPanel();
        CloseLab = new javax.swing.JLabel();
        PaymentPage1Lab = new javax.swing.JLabel();
        MinLab = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        jPanel2.setBackground(new java.awt.Color(0, 0, 0));

        SelectBut.setBackground(new java.awt.Color(0, 0, 0));
        SelectBut.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        SelectBut.setForeground(new java.awt.Color(255, 204, 204));
        SelectBut.setText("Select");
        SelectBut.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 204, 204)));
        SelectBut.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        SelectBut.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SelectButActionPerformed(evt);
            }
        });

        BackLab.setForeground(new java.awt.Color(255, 204, 204));
        BackLab.setText("Back");
        BackLab.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        BackLab.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                BackLabMouseClicked(evt);
            }
        });

        UnitNoLab.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        UnitNoLab.setForeground(new java.awt.Color(255, 204, 204));
        UnitNoLab.setText("Unit No. :");

        UnitCmb.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        UnitCmb.setEnabled(false);

        BlockLab.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        BlockLab.setForeground(new java.awt.Color(255, 204, 204));
        BlockLab.setText("Block:");

        BlockCmb.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "A", "B" }));
        BlockCmb.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        BlockCmb.setPreferredSize(new java.awt.Dimension(50, 22));
        BlockCmb.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BlockCmbActionPerformed(evt);
            }
        });

        FloorLab.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        FloorLab.setForeground(new java.awt.Color(255, 204, 204));
        FloorLab.setText("Floor:");

        FloorCmb.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "01", "02", "03", "04", "05", "06", "07", "08", "09", "10" }));
        FloorCmb.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        FloorCmb.setPreferredSize(new java.awt.Dimension(50, 22));
        FloorCmb.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                FloorCmbActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(112, 112, 112)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(UnitNoLab)
                    .addComponent(FloorLab)
                    .addComponent(BlockLab))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 191, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(UnitCmb, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(BlockCmb, javax.swing.GroupLayout.Alignment.TRAILING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(FloorCmb, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(118, 118, 118))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(SelectBut, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(BackLab)
                        .addGap(295, 295, 295)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(BackLab)
                .addGap(51, 51, 51)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(BlockLab)
                        .addGap(31, 31, 31)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(53, 53, 53)
                                .addComponent(UnitNoLab))
                            .addComponent(FloorLab)))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(BlockCmb, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(34, 34, 34)
                        .addComponent(FloorCmb, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(31, 31, 31)
                        .addComponent(UnitCmb, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 42, Short.MAX_VALUE)
                .addComponent(SelectBut, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(51, 51, 51))
        );

        jPanel1.setBackground(new java.awt.Color(255, 178, 178));

        CloseLab.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        CloseLab.setForeground(new java.awt.Color(255, 255, 255));
        CloseLab.setText("X");
        CloseLab.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        CloseLab.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                CloseLabMouseClicked(evt);
            }
        });

        PaymentPage1Lab.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        PaymentPage1Lab.setForeground(new java.awt.Color(255, 255, 255));
        PaymentPage1Lab.setText("Payment Page");

        MinLab.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        MinLab.setForeground(new java.awt.Color(255, 255, 255));
        MinLab.setText("-");
        MinLab.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        MinLab.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                MinLabMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(PaymentPage1Lab)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(MinLab)
                .addGap(18, 18, 18)
                .addComponent(CloseLab)
                .addGap(23, 23, 23))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(CloseLab, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(MinLab, javax.swing.GroupLayout.DEFAULT_SIZE, 33, Short.MAX_VALUE)
                    .addComponent(PaymentPage1Lab, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(1, 1, 1)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void SelectButActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SelectButActionPerformed
        if(UnitCmb.getItemCount() == 0){
            //Error Message for select an unit
            JOptionPane.showMessageDialog(this,"Please Select an Unit.","Error Message",JOptionPane.ERROR_MESSAGE);  
            
        }else{
            //Store unit no in variable to be used in next form
            UnitNo = UnitCmb.getSelectedItem().toString();
            
            PaymentForm2 pf2 = new PaymentForm2();
            pf2.setVisible(true);
            pf2.pack();
            pf2.setLocationRelativeTo(null);
            pf2.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
            this.setVisible(false);
            
            //Reset the variable
            UnitNoFromMRF2 = null;
        }
    }//GEN-LAST:event_SelectButActionPerformed

    private void CloseLabMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_CloseLabMouseClicked
        System.exit(0);//Close Button
    }//GEN-LAST:event_CloseLabMouseClicked

    private void MinLabMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_MinLabMouseClicked
        this.setState(JFrame.ICONIFIED);//Minimize Button
    }//GEN-LAST:event_MinLabMouseClicked

    private void BlockCmbActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BlockCmbActionPerformed
        try {
            //Connect to database
            DBConnection conn = new DBConnection();
            conn.connection();
            PreparedStatement ps;

            //Declare variables
            String Block, Floor, BlockFloor;
            Block = BlockCmb.getSelectedItem().toString();
            Floor = FloorCmb.getSelectedItem().toString();
            BlockFloor = Block + Floor;

            //Clear combo box
            UnitCmb.removeAllItems();
            UnitCmb.setEnabled(true);

            //SQL Select query to check the username and password
            ps = con.prepareStatement("SELECT `Unit_ID` FROM `unit` WHERE `Unit_ID` LIKE '"+BlockFloor+"%' AND `Outstanding_Balance`='200' AND `Due_Date` IS NOT NULL");
            ResultSet result = ps.executeQuery();

            while(result.next()){
                //Add items into combo box
                UnitCmb.addItem(result.getString("Unit_ID"));
            }
            
            //If the result not found
            if(UnitCmb.getItemCount()==0){
                JOptionPane.showMessageDialog(this,"No unit found!","Search Message", JOptionPane.ERROR_MESSAGE);
                UnitCmb.setEnabled(false);
            }

        } catch (SQLException ex) {
            Logger.getLogger(RegisterUnitForm.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_BlockCmbActionPerformed

    private void FloorCmbActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_FloorCmbActionPerformed
        try {
            //Connect to database
            DBConnection conn = new DBConnection();
            conn.connection();
            PreparedStatement ps;

            //Declare variables
            String Block, Floor, BlockFloor;
            Block = BlockCmb.getSelectedItem().toString();
            Floor = FloorCmb.getSelectedItem().toString();
            BlockFloor = Block + Floor;

            //Clear combo box
            UnitCmb.removeAllItems();
            UnitCmb.setEnabled(true);

            //SQL Select query to check the username and password
            ps = con.prepareStatement("SELECT `Unit_ID` FROM `unit` WHERE `Unit_ID` LIKE '"+BlockFloor+"%' AND `Outstanding_Balance`='200' AND `Due_Date` IS NOT NULL");
            ResultSet result = ps.executeQuery();

            while(result.next()){
                //Add items into combo box
                UnitCmb.addItem(result.getString("Unit_ID"));
            }
            
            //if the result not found
            if(UnitCmb.getItemCount()==0){
                JOptionPane.showMessageDialog(this,"No unit found!","Search Message", JOptionPane.ERROR_MESSAGE);
                UnitCmb.setEnabled(false);
            }

        } catch (SQLException ex) {
            Logger.getLogger(RegisterUnitForm.class.getName()).log(Level.SEVERE, null, ex);
        }

    }//GEN-LAST:event_FloorCmbActionPerformed

    private void BackLabMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BackLabMouseClicked
        StaffMenuForm smf = new StaffMenuForm();
        smf.setVisible(true);
        smf.pack();
        smf.setLocationRelativeTo(null);
        smf.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        this.setVisible(false);
        
        //Reset the variable
        UnitNoFromMRF2 = null;
    }//GEN-LAST:event_BackLabMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PaymentForm1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PaymentForm1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PaymentForm1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PaymentForm1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new PaymentForm1().setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel BackLab;
    private javax.swing.JComboBox<String> BlockCmb;
    private javax.swing.JLabel BlockLab;
    private javax.swing.JLabel CloseLab;
    private javax.swing.JComboBox<String> FloorCmb;
    private javax.swing.JLabel FloorLab;
    private javax.swing.JLabel MinLab;
    private javax.swing.JLabel PaymentPage1Lab;
    private javax.swing.JButton SelectBut;
    private javax.swing.JComboBox<String> UnitCmb;
    private javax.swing.JLabel UnitNoLab;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    // End of variables declaration//GEN-END:variables

    
}
