/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package assignment;

import static assignment.DBConnection.con;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFrame;
import javax.swing.JOptionPane;

/**
 *
 * @author Keith
 */
public class RegisterUnitForm extends javax.swing.JFrame {
    public static String UnitNo;

    /**
     * Creates new form RegisterUnitForm
     */
    public RegisterUnitForm() {
        initComponents();
        
        BlockCmb.requestFocus();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        BlockLab = new javax.swing.JLabel();
        RegisterBut = new javax.swing.JButton();
        UnitNoLab = new javax.swing.JLabel();
        BlockCmb = new javax.swing.JComboBox<>();
        backlab = new javax.swing.JLabel();
        FloorCmb = new javax.swing.JComboBox<>();
        UnitCmb = new javax.swing.JComboBox<>();
        FloorLab = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        CloseLab = new javax.swing.JLabel();
        RegisterUnitPageLab = new javax.swing.JLabel();
        MinLab = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        jPanel2.setBackground(new java.awt.Color(0, 0, 0));

        BlockLab.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        BlockLab.setForeground(new java.awt.Color(255, 204, 204));
        BlockLab.setText("Block:");

        RegisterBut.setBackground(new java.awt.Color(0, 0, 0));
        RegisterBut.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        RegisterBut.setForeground(new java.awt.Color(255, 204, 204));
        RegisterBut.setText("Register");
        RegisterBut.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 204, 204)));
        RegisterBut.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        RegisterBut.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RegisterButActionPerformed(evt);
            }
        });

        UnitNoLab.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        UnitNoLab.setForeground(new java.awt.Color(255, 204, 204));
        UnitNoLab.setText("Available Unit:");

        BlockCmb.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "A", "B" }));
        BlockCmb.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        BlockCmb.setPreferredSize(new java.awt.Dimension(50, 22));
        BlockCmb.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BlockCmbActionPerformed(evt);
            }
        });

        backlab.setForeground(new java.awt.Color(255, 204, 204));
        backlab.setText("Back");
        backlab.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        backlab.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                backlabMouseClicked(evt);
            }
        });

        FloorCmb.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "01", "02", "03", "04", "05", "06", "07", "08", "09", "10" }));
        FloorCmb.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        FloorCmb.setPreferredSize(new java.awt.Dimension(50, 22));
        FloorCmb.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                FloorCmbActionPerformed(evt);
            }
        });

        UnitCmb.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        UnitCmb.setEnabled(false);
        UnitCmb.setPreferredSize(new java.awt.Dimension(50, 22));
        UnitCmb.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                UnitCmbActionPerformed(evt);
            }
        });

        FloorLab.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        FloorLab.setForeground(new java.awt.Color(255, 204, 204));
        FloorLab.setText("Floor:");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(28, 28, 28)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(RegisterBut, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(backlab)
                                .addGap(295, 295, 295))))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(139, 139, 139)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(UnitNoLab, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(FloorLab, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(BlockLab, javax.swing.GroupLayout.Alignment.LEADING))
                        .addGap(76, 76, 76)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(BlockCmb, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(FloorCmb, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(UnitCmb, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(25, 147, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(backlab)
                .addGap(56, 56, 56)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(BlockLab)
                    .addComponent(BlockCmb, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(35, 35, 35)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(FloorLab)
                    .addComponent(FloorCmb, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(42, 42, 42)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(UnitNoLab)
                    .addComponent(UnitCmb, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(46, 46, 46)
                .addComponent(RegisterBut, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(52, Short.MAX_VALUE))
        );

        jPanel1.setBackground(new java.awt.Color(255, 178, 178));

        CloseLab.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        CloseLab.setForeground(new java.awt.Color(255, 255, 255));
        CloseLab.setText("X");
        CloseLab.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        CloseLab.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                CloseLabMouseClicked(evt);
            }
        });

        RegisterUnitPageLab.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        RegisterUnitPageLab.setForeground(new java.awt.Color(255, 255, 255));
        RegisterUnitPageLab.setText("Register Unit Page");

        MinLab.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        MinLab.setForeground(new java.awt.Color(255, 255, 255));
        MinLab.setText("-");
        MinLab.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        MinLab.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                MinLabMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(RegisterUnitPageLab)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(MinLab)
                .addGap(18, 18, 18)
                .addComponent(CloseLab)
                .addGap(23, 23, 23))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(CloseLab, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(MinLab, javax.swing.GroupLayout.DEFAULT_SIZE, 33, Short.MAX_VALUE)
                    .addComponent(RegisterUnitPageLab, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addGroup(layout.createSequentialGroup()
                .addGap(50, 50, 50)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void RegisterButActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RegisterButActionPerformed
        if(UnitCmb.getItemCount() == 0){
            //Error Message for select an unit
            JOptionPane.showMessageDialog(this,"Please Select an Unit.","Error Message",JOptionPane.ERROR_MESSAGE);  
            
        }else{
            //Store unit no in variable to be used in next form
            UnitNo = UnitCmb.getSelectedItem().toString();

            RegisterResidentForm rrf = new RegisterResidentForm();
            rrf.setVisible(true);
            rrf.pack();
            rrf.setLocationRelativeTo(null);
            rrf.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
            this.setVisible(false);
        }
    }//GEN-LAST:event_RegisterButActionPerformed

    private void BlockCmbActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BlockCmbActionPerformed
        try {
            //Connect to database
            DBConnection conn = new DBConnection();
            conn.connection();
            PreparedStatement ps;
            
            //Declare variables
            String Block, Floor, BlockFloor;
            Block = BlockCmb.getSelectedItem().toString();
            Floor = FloorCmb.getSelectedItem().toString();
            BlockFloor = Block + Floor;
            
            //Clear combo box
            UnitCmb.removeAllItems();
            UnitCmb.setEnabled(true);
            
            //SQL Select query to check the username and password
            ps = con.prepareStatement("SELECT `Unit_ID` FROM `unit` WHERE `Unit_ID` LIKE '"+BlockFloor+"%' AND `Resident_ID` IS NULL");
            ResultSet result = ps.executeQuery();
            
            while(result.next()){
                //Add items into combo box
                UnitCmb.addItem(result.getString("Unit_ID"));
            }
            
        } catch (SQLException ex) {
            Logger.getLogger(RegisterUnitForm.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_BlockCmbActionPerformed

    private void backlabMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_backlabMouseClicked
        StaffMenuForm smf = new StaffMenuForm();
        smf.setVisible(true);
        smf.pack();
        smf.setLocationRelativeTo(null);
        smf.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        this.setVisible(false);
    }//GEN-LAST:event_backlabMouseClicked

    private void FloorCmbActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_FloorCmbActionPerformed
        try {
            //Connect to database
            DBConnection conn = new DBConnection();
            conn.connection();
            PreparedStatement ps;
            
            //Declare variables
            String Block, Floor, BlockFloor;
            Block = BlockCmb.getSelectedItem().toString();
            Floor = FloorCmb.getSelectedItem().toString();
            BlockFloor = Block + Floor;
            
            //Clear combo box
            UnitCmb.removeAllItems();
            UnitCmb.setEnabled(true);
            
            //SQL Select query to check the username and password
            ps = con.prepareStatement("SELECT `Unit_ID` FROM `unit` WHERE `Unit_ID` LIKE '"+BlockFloor+"%' AND `Resident_ID` IS NULL");
            ResultSet result = ps.executeQuery();
            
            while(result.next()){
                //Add items into combo box
                UnitCmb.addItem(result.getString("Unit_ID"));
            }
            
        } catch (SQLException ex) {
            Logger.getLogger(RegisterUnitForm.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        
    }//GEN-LAST:event_FloorCmbActionPerformed

    private void UnitCmbActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_UnitCmbActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_UnitCmbActionPerformed

    private void CloseLabMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_CloseLabMouseClicked
        System.exit(0);//Close Button
    }//GEN-LAST:event_CloseLabMouseClicked

    private void MinLabMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_MinLabMouseClicked
        this.setState(JFrame.ICONIFIED);//Minimize Button
    }//GEN-LAST:event_MinLabMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(RegisterUnitForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(RegisterUnitForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(RegisterUnitForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(RegisterUnitForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new RegisterUnitForm().setVisible(true);
        });
    }
    
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> BlockCmb;
    private javax.swing.JLabel BlockLab;
    private javax.swing.JLabel CloseLab;
    private javax.swing.JComboBox<String> FloorCmb;
    private javax.swing.JLabel FloorLab;
    private javax.swing.JLabel MinLab;
    private javax.swing.JButton RegisterBut;
    private javax.swing.JLabel RegisterUnitPageLab;
    private javax.swing.JComboBox<String> UnitCmb;
    private javax.swing.JLabel UnitNoLab;
    private javax.swing.JLabel backlab;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    // End of variables declaration//GEN-END:variables
}
