/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package assignment;

/**
 *
 * @author Keith
 */
import static assignment.DBConnection.con;
import java.awt.event.KeyEvent;
import java.security.MessageDigest;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.util.Date;
import java.util.regex.Pattern;
import javax.swing.JFrame;
import javax.swing.JOptionPane;

public class ResidentLoginForm extends javax.swing.JFrame {
    public static String Resident_Name,Resident_Email,Resident_PhoneNumber,Resident_ID,Unit_ID,Account_Status;
    public static int Outstanding_Balance;
    public static Date Due_Date;
    /**
     * Creates new form ResidentLoginForm
     */
    public ResidentLoginForm() {
        initComponents();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        UsernameLab = new javax.swing.JLabel();
        TitleLab = new javax.swing.JLabel();
        PasswordLab = new javax.swing.JLabel();
        UsernameTxt = new javax.swing.JTextField();
        PasswordTxt = new javax.swing.JPasswordField();
        LoginBut = new javax.swing.JButton();
        BackBut = new javax.swing.JButton();
        ClearBut = new javax.swing.JButton();
        ShowPassChk = new javax.swing.JCheckBox();
        jPanel1 = new javax.swing.JPanel();
        CloseLab = new javax.swing.JLabel();
        ResidentLoginPageLab = new javax.swing.JLabel();
        MinLab = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        jPanel2.setBackground(new java.awt.Color(0, 0, 0));

        UsernameLab.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        UsernameLab.setForeground(new java.awt.Color(255, 204, 204));
        UsernameLab.setText("Username :");

        TitleLab.setFont(new java.awt.Font("Arial Black", 0, 26)); // NOI18N
        TitleLab.setForeground(new java.awt.Color(255, 255, 255));
        TitleLab.setText("Welcome To Resident Login Page");
        TitleLab.setToolTipText("");

        PasswordLab.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        PasswordLab.setForeground(new java.awt.Color(255, 204, 204));
        PasswordLab.setText("Password :");

        UsernameTxt.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                UsernameTxtKeyTyped(evt);
            }
        });

        PasswordTxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PasswordTxtActionPerformed(evt);
            }
        });

        LoginBut.setBackground(new java.awt.Color(0, 0, 0));
        LoginBut.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        LoginBut.setForeground(new java.awt.Color(255, 204, 204));
        LoginBut.setText("Login");
        LoginBut.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 204, 204)));
        LoginBut.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        LoginBut.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LoginButActionPerformed(evt);
            }
        });

        BackBut.setBackground(new java.awt.Color(0, 0, 0));
        BackBut.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        BackBut.setForeground(new java.awt.Color(255, 204, 204));
        BackBut.setText("Back");
        BackBut.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 204, 204)));
        BackBut.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        BackBut.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BackButActionPerformed(evt);
            }
        });

        ClearBut.setBackground(new java.awt.Color(0, 0, 0));
        ClearBut.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        ClearBut.setForeground(new java.awt.Color(255, 204, 204));
        ClearBut.setText("Clear");
        ClearBut.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 204, 204)));
        ClearBut.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        ClearBut.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ClearButActionPerformed(evt);
            }
        });

        ShowPassChk.setBackground(new java.awt.Color(0, 0, 0));
        ShowPassChk.setForeground(new java.awt.Color(255, 204, 204));
        ShowPassChk.setText("Show Password");
        ShowPassChk.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        ShowPassChk.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ShowPassChkActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(68, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(22, 22, 22)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(UsernameLab)
                            .addComponent(PasswordLab)
                            .addComponent(LoginBut, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(UsernameTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 270, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(PasswordTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 270, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(ShowPassChk))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                                .addComponent(ClearBut, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(52, 52, 52)
                                .addComponent(BackBut, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(91, 91, 91))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(TitleLab)
                        .addGap(59, 59, 59))))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addComponent(TitleLab)
                .addGap(51, 51, 51)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(UsernameLab)
                    .addComponent(UsernameTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(PasswordLab)
                    .addComponent(PasswordTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(ShowPassChk)
                .addGap(31, 31, 31)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(LoginBut, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(BackBut, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ClearBut, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(40, Short.MAX_VALUE))
        );

        jPanel1.setBackground(new java.awt.Color(255, 178, 178));

        CloseLab.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        CloseLab.setForeground(new java.awt.Color(255, 255, 255));
        CloseLab.setText("X");
        CloseLab.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        CloseLab.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                CloseLabMouseClicked(evt);
            }
        });

        ResidentLoginPageLab.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        ResidentLoginPageLab.setForeground(new java.awt.Color(255, 255, 255));
        ResidentLoginPageLab.setText("Resident Login Page");

        MinLab.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        MinLab.setForeground(new java.awt.Color(255, 255, 255));
        MinLab.setText("-");
        MinLab.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        MinLab.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                MinLabMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(ResidentLoginPageLab)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(MinLab)
                .addGap(18, 18, 18)
                .addComponent(CloseLab)
                .addGap(23, 23, 23))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(CloseLab, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(MinLab, javax.swing.GroupLayout.DEFAULT_SIZE, 33, Short.MAX_VALUE)
                    .addComponent(ResidentLoginPageLab, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addGroup(layout.createSequentialGroup()
                .addGap(58, 58, 58)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void CloseLabMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_CloseLabMouseClicked
        System.exit(0);//Close Button
    }//GEN-LAST:event_CloseLabMouseClicked

    private void MinLabMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_MinLabMouseClicked
        this.setState(JFrame.ICONIFIED);//Minimize Button
    }//GEN-LAST:event_MinLabMouseClicked

    private void LoginButActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LoginButActionPerformed
        //Connect to database
        DBConnection conn = new DBConnection();
        conn.connection();
        
        //Login using Static method programming
        String username, password;
        username = UsernameTxt.getText();
        password = String.valueOf(PasswordTxt.getPassword());
        
        if(Pattern.matches(".*[A-Z].*",password)){
            int option = JOptionPane.showConfirmDialog(
                    null,
                    "Case sensitive.\nProceed with the uppercase letter in password?",
                    "Confirmation Message",
                    JOptionPane.YES_NO_OPTION,
                    JOptionPane.QUESTION_MESSAGE);
            
                if(option == 0){
                    ResidentLogin(username,password);
                    this.setVisible(false);
                }
                
        }else{
            ResidentLogin(username,password);
            this.setVisible(false);
        }       
    }//GEN-LAST:event_LoginButActionPerformed

    private void BackButActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BackButActionPerformed
        WelcomeForm wf = new WelcomeForm();
        wf.setVisible(true);
        wf.pack();
        wf.setLocationRelativeTo(null);
        wf.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        this.dispose();
    }//GEN-LAST:event_BackButActionPerformed

    private void ClearButActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ClearButActionPerformed
        ResidentLoginForm rlf = new ResidentLoginForm();
        rlf.setVisible(true);
        rlf.pack();
        rlf.setLocationRelativeTo(null);
        rlf.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        this.dispose();
    }//GEN-LAST:event_ClearButActionPerformed

    private void PasswordTxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PasswordTxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_PasswordTxtActionPerformed

    private void ShowPassChkActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ShowPassChkActionPerformed
        if(ShowPassChk.isSelected()){
            PasswordTxt.setEchoChar((char)0);
        }else{
            PasswordTxt.setEchoChar('*');
        }

    }//GEN-LAST:event_ShowPassChkActionPerformed

    private void UsernameTxtKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_UsernameTxtKeyTyped
        //Validate the user can type Alpabet and space only
        char c = evt.getKeyChar();
        if(!(Character.isLowerCase(c) || c== KeyEvent.VK_BACK_SPACE || c== KeyEvent.VK_DELETE || Character.isWhitespace(c))){
            evt.consume();
            JOptionPane.showMessageDialog(this,"Lower Case Alphabet Only!","Validation Message",JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_UsernameTxtKeyTyped

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ResidentLoginForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ResidentLoginForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ResidentLoginForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ResidentLoginForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new ResidentLoginForm().setVisible(true);
        });
    }
    
    public static void ResidentLogin(String Username,String Password){
        PreparedStatement ps,ps1;
        int Check = 0;
        
        try{
            
            //*****Encryt the Password*****
            String HashedPassword;
            
            // Create MessageDigest instance for MD5
            MessageDigest md = MessageDigest.getInstance("MD5");
            //Add password bytes to digest
            md.update(Password.getBytes());
            //Get the hash's bytes
            byte[] bytes = md.digest();
            
            //This bytes[] has bytes in decimal format;
            //Convert it to hexadecimal format
            StringBuilder sb = new StringBuilder();
            for(int i=0; i< bytes.length ;i++)
            {
                sb.append(Integer.toString((bytes[i] & 0xff) + 0x100, 16).substring(1));
            }
            
            //Get complete hashed password in hexadecimal format
            HashedPassword = sb.toString();
                        
            
            //SQL Select query to check the username and password
            ps = con.prepareStatement("SELECT * FROM `resident` WHERE `Resident_Name`=? AND `Resident_Password`=?");
            ps.setString(1,Username);
            ps.setString(2,String.valueOf(HashedPassword));
            ResultSet result = ps.executeQuery();
            
            if(result.next()){
                Resident_Name = result.getString("Resident_Name");
                Resident_ID = result.getString("Resident_ID");
                Resident_PhoneNumber = result.getString("Resident_Phone_Number");
                Resident_Email = result.getString("Resident_Email");
                Account_Status = result.getString("Account_Status");
                Check =1;
            }
            
            if(Check == 1){
            //SQL Select query to get the info from Unit table
            ps1 = con.prepareStatement("SELECT * FROM `unit` WHERE `Resident_ID`=?");
            ps1.setString(1,Resident_ID);
            ResultSet result1 = ps1.executeQuery();
            
            if(result1.next()){
                Unit_ID = result1.getString("Unit_ID");
                Outstanding_Balance = result1.getInt("Outstanding_Balance");
                Due_Date = result1.getDate("Due_Date");
                Check =2;
            }
            }
                                  
                if(Check == 2){
                    
                    if(Account_Status.contentEquals("Active")){
                        Check = 3;
                    }else if(Account_Status.contentEquals("Deactivated")){
                        Check = 4;
                    }
                }
                
                if(Check == 3){
                    //Login successfully message
                    JOptionPane.showMessageDialog(null,"Login Successfully!","Login Message",JOptionPane.INFORMATION_MESSAGE);

                    //Open the next form
                    ResidentMenuForm rmf = new ResidentMenuForm();
                    rmf.setVisible(true);
                    rmf.pack();
                    rmf.setLocationRelativeTo(null);
                    rmf.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
                
                }else if(Check == 4){
                    //Message to remind resident to pay fees
                    JOptionPane.showMessageDialog(null,"Account deactivated!\nPlease pay the fees at the administration counter.","Login Message",JOptionPane.WARNING_MESSAGE);
                    
                    //Reopen the Resident Login Form
                    ResidentLoginForm rlf = new ResidentLoginForm();
                    rlf.setVisible(true);
                    rlf.pack();
                    rlf.setLocationRelativeTo(null);
                    rlf.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
                                                
                }else{
                    //Error message for invalid username/password
                    JOptionPane.showMessageDialog(null,"Wrong Username or Password!","Login Message",JOptionPane.ERROR_MESSAGE);

                    //Reopen the Resident Login Form
                    ResidentLoginForm rlf = new ResidentLoginForm();
                    rlf.setVisible(true);
                    rlf.pack();
                    rlf.setLocationRelativeTo(null);
                    rlf.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
                }         
            
       
        }catch (Exception e){
            System.out.println(e);
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BackBut;
    private javax.swing.JButton ClearBut;
    private javax.swing.JLabel CloseLab;
    private javax.swing.JButton LoginBut;
    private javax.swing.JLabel MinLab;
    private javax.swing.JLabel PasswordLab;
    private javax.swing.JPasswordField PasswordTxt;
    private javax.swing.JLabel ResidentLoginPageLab;
    private javax.swing.JCheckBox ShowPassChk;
    private javax.swing.JLabel TitleLab;
    private javax.swing.JLabel UsernameLab;
    private javax.swing.JTextField UsernameTxt;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    // End of variables declaration//GEN-END:variables
}
